---
ms.openlocfilehash: 5f11e465a529e3f6cb14658095e0fe0a69ce6115
ms.sourcegitcommit: 82ed9ded42c47064c90ab6fe717893447cd48796
ms.translationtype: HT
ms.contentlocale: ar-SA
ms.lasthandoff: 10/19/2020
ms.locfileid: "6071777"
---
<span data-ttu-id="fb4ed-101">يتم وضع عبارات الخطأ قبل الاختبار لإملاء ما يجب عرضه عند نجاح الاختبار أو فشله.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-101">Error statements are developed before testing to dictate what should be displayed when a test passes or fails.</span></span> <span data-ttu-id="fb4ed-102">يمكنك معالجة الأخطاء باستخدام العبارات `Throw` و`Try...catch` و`Finally` و`Retry` لمعالجة الاستثناءات.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-102">You can handle errors by using the `Throw`, `Try...catch`, `Finally`, and `Retry` statements to handle exceptions.</span></span> <span data-ttu-id="fb4ed-103">الاستثناء هو انتقال سريع منظم بعيداً عن تشغيل الكود.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-103">An exception is a regulated jump away from the code run.</span></span>
 
<span data-ttu-id="fb4ed-104">تُستخدم الكلمة الأساسية `throw` لطرح قيمة تعداد استثنائية.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-104">The `throw` keyword is used to throw an exception enum value.</span></span> <span data-ttu-id="fb4ed-105">على سبيل المثال، سيتم استخدام العبارة `throw Exception::error;` لطرح استثناء خطأ.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-105">For example, the statement `throw Exception::error;` would be used to throw an error exception.</span></span> <span data-ttu-id="fb4ed-106">نوصي باستخدام الطريقة `Global::error` بدلاً من `Exception::error`.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-106">We recommend that you use the `Global::error` method instead of the `Exception::error`.</span></span> <span data-ttu-id="fb4ed-107">يمكن للطريقة `Global::error` كتابة رسالة إلى سجل المعلومات عند طرح استثناء خطأ وتحويل التسمية إلى نص تلقائياً.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-107">The `Global::error` can write a message to the Infolog when an error exception is thrown and convert a label automatically into text.</span></span> <span data-ttu-id="fb4ed-108">يمكنك أيضاً كتابة `Global::error("Error message.")` بالطريقة `error("Error
message.")`.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-108">You can also write the `Global::error("Error message.")` as `error("Error
message.")`.</span></span>

<span data-ttu-id="fb4ed-109">تُستخدم الكلمات الأساسية `try...catch` لمعالجة استثناء تم طرحه من خلال الالتقاط.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-109">The `try...catch` keywords are used to process a thrown exception through the catch.</span></span> <span data-ttu-id="fb4ed-110">يتم تشغيل الكود في كتلة الكود `try`.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-110">The code is run in the `try` code block.</span></span>
<span data-ttu-id="fb4ed-111">في حالة طرح خطأ، سيقوم الكود بالانتقال السريع إلى تشغيل كتل كود الالتقاط بشكل تسلسلي لمعرفة ما إذا تم تحديد الخطأ الذي تم طرحه لمعالجة الخطأ.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-111">If an error is thrown, the code will jump to run the catch code blocks sequentially to see if the thrown error is specified to handle the error.</span></span> <span data-ttu-id="fb4ed-112">ويُعد من الممارسات الشائعة أن تجعل عبارة الالتقاط تقوم بمعالجة قيمة التعداد `Exception::Error` وترك عبارة التقاط واحدة فارغة لالتقاط أي خطأ غير محدد.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-112">It is a common practice to have the first catch statement handle the `Exception::Error` enum value and leave one catch blank to catch any unspecified error.</span></span> <span data-ttu-id="fb4ed-113">يمكن استخدام الكلمة الأساسية `Finally` مع عبارة `Try...catch`.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-113">The `Finally` keyword can be used with the `Try...catch` statement.</span></span> <span data-ttu-id="fb4ed-114">سيتم تشغيل الكود الموجود في كتلة الكود `finally` عندما يترك الكود الكتلة `try` إما بشكل عادي أو بسبب حدوث خطأ.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-114">The code in the `finally` code block will run when the code leaves the `try` block either normally or because of an error.</span></span> <span data-ttu-id="fb4ed-115">انظر الكود في المثال الآتي:</span><span class="sxs-lookup"><span data-stu-id="fb4ed-115">See the following code example.</span></span>

```xpp
try
{
  // Code here.
}
catch (Exception::Numeric)
{
  info("Caught a Numeric exception.");
}
catch
{
  info("Caught an exception.");
}
finally
{
  // Executed no matter how the try block exits.
}
```

<span data-ttu-id="fb4ed-116">يمكن كتابة الكلمة الأساسية `retry` فقط في الكتلة `catch`.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-116">The `retry` keyword can only be written in a `catch` block.</span></span> <span data-ttu-id="fb4ed-117">ويؤدي ذلك إلى انتقال الكود مرة أخرى إلى أول سطر في كتلة الكود `try`.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-117">This causes the code to jump back to the first line in the `try` code block.</span></span> <span data-ttu-id="fb4ed-118">يجب استخدام `retry` عندما يمكن حل المشكلة من خلال الكود.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-118">A `retry` should be used when the issue can be fixed through code.</span></span> <span data-ttu-id="fb4ed-119">تعمل الكتلة `retry` على منح الكود فرصة إضافية للنجاح وتعرض سجل معلومات عندما يتم بدء تشغيل الكتلة `try`.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-119">The `retry` gives the code an additional chance to succeed and will display an Infolog when the `try` block started to run.</span></span> <span data-ttu-id="fb4ed-120">يجب أن تتأكد من أن عبارة `retry` لا تتسبب في تكرار لا نهائي.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-120">You must make sure that the `retry` statement does not cause an infinite loop.</span></span> <span data-ttu-id="fb4ed-121">نوصي بتضمين متغير في الكتلة `try` لاختباره إذا كنت في حلقة لا نهائية.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-121">We recommend that you include a variable in the `try` block to test if you are in an infinite loop.</span></span>

<span data-ttu-id="fb4ed-122">يمكنك طرح العديد من استثناءات الخطأ:</span><span class="sxs-lookup"><span data-stu-id="fb4ed-122">You can throw several error exceptions:</span></span>

-   <span data-ttu-id="fb4ed-123">**Break** -قام المستخدم بالضغط على Break أو Ctrl + C.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-123">**Break** - The user pressed Break or Ctrl + C.</span></span>
-   <span data-ttu-id="fb4ed-124">**CLRError** - حدث الخطأ في أثناء استخدام وظيفة CLR.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-124">**CLRError** - The error occurred while the CLR functionality was being used.</span></span>
-   <span data-ttu-id="fb4ed-125">**CodeAccessSecurity** - حدث خطأ في أثناء استخدام الأسلوب `CodeAccessPermission.demand`.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-125">**CodeAccessSecurity** - An error occurred while the `CodeAccessPermission.demand` method was being used.</span></span>
-   <span data-ttu-id="fb4ed-126">**DDEerror** - حدث خطأ في أثناء استخدام فئة نظام DDE.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-126">**DDEerror** - An error occurred while the DDE system class was being used.</span></span>
-   <span data-ttu-id="fb4ed-127">**Deadlock** - حدث توقف تام لقاعدة البيانات بسبب وجود حركات متعددة تنتظر كل منها الأخرى.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-127">**Deadlock** - A database deadlock occurred because several transactions are waiting for each other.</span></span>
-   <span data-ttu-id="fb4ed-128">**DuplicateKeyException** - حدث خطأ في الحركة التي تستخدم "تحكم التزامن المعزز بحماية التغييرات".</span><span class="sxs-lookup"><span data-stu-id="fb4ed-128">**DuplicateKeyException** - An error occurred in a transaction that is using Optimistic Concurrency Control.</span></span> <span data-ttu-id="fb4ed-129">يمكن إعادة محاولة الحركة.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-129">The transaction can be retried.</span></span>
-   <span data-ttu-id="fb4ed-130">**DuplicateKeyExceptionNotRecovered** - حدث خطأ في الحركة التي تستخدم "تحكم التزامن المعزز بحماية التغييرات".</span><span class="sxs-lookup"><span data-stu-id="fb4ed-130">**DuplicateKeyExceptionNotRecovered** - An error occurred in a transaction that is using Optimistic Concurrency Control.</span></span> <span data-ttu-id="fb4ed-131">لن تتم إعادة محاولة الكود، ولا يمكن الكشف عن هذا الاستثناء في الحركة.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-131">The code won't be retried, and this exception cannot be caught in a transaction.</span></span>
-   <span data-ttu-id="fb4ed-132">**Error** - حدث خطأ فادح.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-132">**Error** - A fatal error occurred.</span></span> <span data-ttu-id="fb4ed-133">تم إيقاف الحركة.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-133">The transaction has been stopped.</span></span>
-   <span data-ttu-id="fb4ed-134">**Internal** - حدث خطأ داخلي في نظام التطوير.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-134">**Internal** - An internal error occurred in the development system.</span></span>
-   <span data-ttu-id="fb4ed-135">**Numeric** - حدث خطأ عند استخدام الوظيفة `str2int` أو `str2int64` أو `str2num`.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-135">**Numeric** - An error occurred when the `str2int`, `str2int64`, or `str2num` function was used.</span></span>
-   <span data-ttu-id="fb4ed-136">**UpdateConflict** - حدث خطأ في الحركة أثناء التحديث.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-136">**UpdateConflict** - An error occurred in a transaction during an update.</span></span>
-   <span data-ttu-id="fb4ed-137">**UpdateConflictNotRecovered** - حدث خطأ في الحركة أثناء التحديث.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-137">**UpdateConflictNotRecovered** - An error occurred in a transaction during an update.</span></span> <span data-ttu-id="fb4ed-138">تتعذر إعادة محاولة هذا الاستثناء.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-138">This exception cannot be retried.</span></span>
-   <span data-ttu-id="fb4ed-139">**TransientSQLConnectionError** - حدث خطأ في أثناء تشغيل الاستعلام.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-139">**TransientSQLConnectionError** - An error occurred during the query run.</span></span> <span data-ttu-id="fb4ed-140">سيتم إلغاء الحركة.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-140">The transaction will be canceled.</span></span> <span data-ttu-id="fb4ed-141">لن يتم اكتشاف هذا الاستثناء داخل الحركة.</span><span class="sxs-lookup"><span data-stu-id="fb4ed-141">This exception will not be caught within a transaction.</span></span>
